### ISSUE TITLE
Problem with  libfftw.so.2

### ISSUE THREAD

**Issue by PAULGOYES** [PyLops/curvelops#1]
It seems I had installed correctly all the dependencies. 
  Running setup.py install for curvelops ... done
Successfully installed curvelops-0.1 numpy-1.19.5 pylops-1.13.0 scipy-1.5.4

but.. when I open the python3 and try to import the library I have the next problem with libfftw.so.2

>>> import curvelops.fdct2d_wrapper as ct
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/.local/lib/python3.6/site-packages/curvelops/__init__.py", line 1, in <module>
    from .curvelops import *
  File "/home/paul/.local/lib/python3.6/site-packages/curvelops/curvelops.py", line 13, in <module>
    from .fdct2d_wrapper import *
ImportError: libfftw.so.2: cannot open shared object file: No such file or directory
>>> import curvelops as cl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/paul/.local/lib/python3.6/site-packages/curvelops/__init__.py", line 1, in <module>
    from .curvelops import *
  File "/home/paul/.local/lib/python3.6/site-packages/curvelops/curvelops.py", line 13, in <module>
    from .fdct2d_wrapper import *
ImportError: libfftw.so.2: cannot open shared object file: No such file or directory

can you help me please ?

**Comment by PAULGOYES** [comment]
<pre><font color="#8AE234"><b>paul@paul</b></font>:<font color="#729FCF"><b>~/fftw-2.1.5/lib</b></font>$ ls -l
total 1244
-rw-r--r-- 1 root paul 419818 may 14 23:21 libfftw.a
-rwxr-xr-x 1 root paul    721 may 14 23:21 <font color="#8AE234"><b>libfftw.la</b></font>
lrwxrwxrwx 1 root paul     16 may 14 23:21 <font color="#34E2E2"><b>libfftw.so</b></font> -&gt; <font color="#8AE234"><b>libfftw.so.2.0.7</b></font>
lrwxrwxrwx 1 root paul     16 may 14 23:21 <font color="#34E2E2"><b>libfftw.so.2</b></font> -&gt; <font color="#8AE234"><b>libfftw.so.2.0.7</b></font>
-rwxr-xr-x 1 root paul 251664 may 14 23:21 <font color="#8AE234"><b>libfftw.so.2.0.7</b></font>
-rw-r--r-- 1 root paul 371686 may 14 23:21 librfftw.a
-rwxr-xr-x 1 root paul    728 may 14 23:21 <font color="#8AE234"><b>librfftw.la</b></font>
lrwxrwxrwx 1 root paul     17 may 14 23:21 <font color="#34E2E2"><b>librfftw.so</b></font> -&gt; <font color="#8AE234"><b>librfftw.so.2.0.7</b></font>
lrwxrwxrwx 1 root paul     17 may 14 23:21 <font color="#34E2E2"><b>librfftw.so.2</b></font> -&gt; <font color="#8AE234"><b>librfftw.so.2.0.7</b></font>
-rwxr-xr-x 1 root paul 216984 may 14 23:21 <font color="#8AE234"><b>librfftw.so.2.0.7</b></font>
</pre>

**Comment by mrava87** [comment]
Hi, 
Sorry for the slow reply.

Can I ask how you installed curvelops, using the python -m pip install ... command or cloning the repo?

And did you make sure to set the Environ variables pointing to where you have installed FFTW?

And which operative system are you on?

**Comment by mrava87** [comment]
I cannot guarantee this is a bullet proof installation but I just rerun it on a new Linux machine yesterday and worked: https://github.com/DIG-Kaust/conda_envs/blob/main/install_curvelops.sh

Have a look if you spot any difference with your installation recipe.

**Comment by PAULGOYES** [comment]
Hi Matteo, thanks. The shell script was very hopeful for me, now I have correctly installed curvelops. Works perfect for me in ubuntu 20.04.2 LTS

Just a few comments about the script: 

1. It seems not so necessary to use gcc-4.8 and g++-4.8. Instead, I used version 9.3.0. (but was because I cannot install the 4.8 version), however, works well with the 9.3.0 version.
2. for curvelab it Is necessary to modify the file "makefile.ops" in order to set the path for FFTW.
3. soon I will rec a video with the step-by-step. Because I know it can help others.

someday maybe PyLops can implement the seislet transform.

**Comment by mrava87** [comment]
Fantastic!

1. good to know. It was our experience we needed an older gcc, great it works with 9.3.0 (I’ll give it a try myself at installing it with it).
2. Indeed, I did write a comment, not sure if/how this can be easily automated (any idea is welcome)
3. That would be perfect and we can add a link to in the README.

We do have reimplemented the seislet transform: https://pylops.readthedocs.io/en/latest/api/generated/pylops.signalprocessing.Seislet.html#pylops.signalprocessing.Seislet

In Madagascar they have 3 bases, we so far have only the simplest 2. On the other hand, when I last tried using the one in Madagascar it seemed to me there was no way it would pass the dottest, whilst our adjoint does meaning you can use it with any iterative solver not just with specialized ones like POCS :)

**Comment by PAULGOYES** [comment]
Hi Matteo, 

Here is my installation step-by-step, (in spanish). Maybe It can help someone else to install curvelops in Ubuntu.
Maybe soon I will create the same video in english.
https://www.youtube.com/watch?v=LAFkknyOpGY

**Comment by cako** [comment]
Quedó muy chevere :) Gracias @PAULGOYES

**Comment by mrava87** [comment]
Fantastic!
Let’s add this link to our README. Even if people don’t understand Spanish following what happens on the terminal should help a lot already.

@cako you happy to add it or shall I?

**Comment by cako** [comment]
Done!
