### ISSUE TITLE
How to use this toolbox to process data in [B, C, H, W] format

### ISSUE THREAD

**Issue by nkusyl** [PyLops/curvelops#22]
Thanks for your great work, I am confused, how to use this toolbox to process data in [B, C, H, W] format？

**Comment by cako** [comment]
The base example in the readme should work pretty much unmodified:

```python
import numpy as np
import curvelops as cl

B, C, H, W = 8, 3, 100, 50
x = np.random.randn(B, C, H, W)
FDCT = cl.FDCT2D(dims=x.shape)
c = FDCT @ x  # This is a (B, C, N) shaped array, N is the number of curvelet coefficients
xinv = FDCT.H @ c
np.testing.assert_allclose(x, xinv)
```

If you want to understand how the curvelet coefficients are organized (what they "mean") have a look at these examples:

https://pylops.github.io/curvelops/gallery/plot_sigmoid_coefficients.html
https://github.com/PyLops/curvelops/blob/main/notebooks/Desmystifying_Curvelets.ipynb

**Comment by nkusyl** [comment]
Thank you for your answer, your answer is very important to me
