### ISSUE TITLE
CurveLab down?

### ISSUE THREAD

**Issue by jecampagne** [PyLops/curvelops#23]
Hello,

I would be glad to use your code, but even after get a registration approval to get `CurveLab-2.1.3.tar.gz`
the link `http://curvelet.org/download-secure.php?file=CurveLab-2.1.3.tar.gz` is not working. At least I do not get 
anything on any browser as well as wget or curl on linux.

As I have never used CurveLab before, I am asking you if on your side you get access to the current  CurveLab-2.1.3.tar.gz?
I do not ask for the tarball, it just to see if I'm doing something wrong on my side ?

Thanks for your help.
Jean-Eric

**Comment by cako** [comment]
Hi @jecampagne thanks for the heads up. It is also no working for me. I have let the maintainers know. I recommend looking into the following projects that can provide similar transforms:
https://www.kymat.io/
https://pytorch-wavelets.readthedocs.io

**Comment by jecampagne** [comment]
Thanks a lot. BTW do you know a "bandlet" code?

**Comment by cako** [comment]
I don't know any unfortunately. Stéphane Mallat, one of the creators of the bandlet transform later developed the scattering transform and ScatNet which later was absorbed by Kymatio. His [research group](https://www.di.ens.fr/data/software/) does not list any bandlet code.
